version: '3.8'

services:
  # Backend service
  todo-backend:
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "4000:3000" # Expose port 3000 of the backend to port 4000 on the host
    networks:
      - todo-network
    depends_on:
      - mongo
      - redis

  # Frontend service
  todo-frontend:
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "80:80"  # Expose frontend on port 80
    networks:
      - todo-network
    depends_on:
      - todo-backend

  # Nginx service
  nginx:
    image: nginx:latest
    container_name: nginx-container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./todo-frontend/build:/usr/share/nginx/html
    ports:
      - "80:80"  # Expose nginx on port 80
    networks:
      - todo-network
    depends_on:
      - todo-frontend

  # MongoDB service
  mongo:
    image: mongo:6.0
    container_name: todo-mongo
    ports:
      - "27017:27017"
    networks:
      - todo-network

  # Redis service
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge
